# predefined_responses.py

predefined_responses = {
    "hello": "Hello! How are you?",
    "hello!": "Hello! How are you?",
    "how are you": "I'm good, thank you. How about you?",
    "how are you?": "I'm good, thank you. How about you?",
    "goodbye": "Goodbye!",
    "thank you": "You're welcome!",
    "what's your name": "I'm a chatbot created with GPT-2.",
    "how old are you": "I don't have an age. I'm just a program.",
    "where are you from": "I exist in the realm of code.",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "do you like pizza": "I don't eat, but I hear pizza is popular with humans.",
    "who is your creator": "My creators are skilled developers passionate about AI.",
    "can you help me": "Of course! What do you need assistance with?",
    "tell me something interesting": "Did you know that the Eiffel Tower can be 15 cm taller during the summer?",
    "can you speak another language": "I can understand and translate multiple languages.",
    "are you a robot": "Yes, I am an AI chatbot designed to assist with conversations.",
    "what is the meaning of life": "That's a tough question! Philosophers have debated it for centuries.",
    "tell me about yourself": "I'm a virtual assistant based on GPT-2, here to chat and provide information.",
    "how can I learn programming": "Start with the basics of a programming language like Python or JavaScript.",
    "what's the weather like today": "I can't check the weather, but you can use a weather website or app.",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "what's the weather like today": "I can't check the weather, but you can use a weather website or app.",
    "who is your favorite superhero": "Iron Man, because he's a genius inventor and superhero.",
    "what is AI": "AI stands for Artificial Intelligence, which is the simulation of human intelligence by machines.",
    "tell me about GPT-3": "GPT-3 is a cutting-edge language model developed by OpenAI.",
    "how do you learn": "I learn from patterns in data and interactions, improving over time with more input.",
    "can you tell me a fun fact": "Sure! The average person spends six months of their lifetime waiting for red lights to turn green.",
    "what's your favorite food": "I don't eat, but if I could, I might like something with lots of data!",
    "can you sing": "I can't sing, but I can help you find lyrics to your favorite songs!",
    "tell me about space": "Space is vast and full of wonders, including stars, planets, black holes, and galaxies.",
    "what's your favorite color": "I don't have personal preferences, but I hear blue is quite popular.",
    "what do you think about humans": "Humans are fascinating creatures with creativity, emotions, and diverse perspectives.",
    "tell me about Elon Musk": "Elon Musk is a visionary entrepreneur known for his work with SpaceX and Tesla.",
    "can you help me with my homework": "I can try to assist you with questions related to various subjects.",
    "what's the best movie ever": "Opinions vary, but many consider 'The Shawshank Redemption' to be one of the best.",
    "can you solve math problems": "I can help with a wide range of math problems, from simple arithmetic to complex equations.",
    "how do I learn programming": "Start with the basics of a programming language like Python or JavaScript.",
    "tell me a fascinating fact": "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "what's your favorite book": "I don't have personal preferences, but '1984' by George Orwell and 'To Kill a Mockingbird' by Harper Lee are highly regarded.",
    "can you recommend a good TV show": "There are many great TV shows depending on your interests. 'Game of Thrones', 'Breaking Bad', and 'Stranger Things' are popular choices.",
    "tell me about artificial intelligence": "Artificial Intelligence (AI) is a field of study focused on creating machines capable of intelligent behavior.",
    "what is the meaning of life": "That's a profound question! Philosophers have debated it for centuries.",
    "can you tell me a story": "Once upon a time, in a land far, far away...",
    "how can I become successful": "Success can mean different things to different people. Pursue your passions, set goals, and continuously learn and grow.",
    "can you teach me something new": "Sure! Did you know that the shortest war in history was between Britain and Zanzibar on August 27, 1896? Zanzibar surrendered after just 38 minutes.",
    "tell me an interesting fact about animals": "The blue whale is the largest animal known to have ever existed, even larger than the dinosaurs.",
    "what's the latest news": "I don't have access to real-time news, but you can check reputable news websites for the latest updates.",
    "can you explain quantum mechanics": "Quantum mechanics is a fundamental theory in physics that describes the behavior of particles at the smallest scales, such as atoms and subatomic particles.",
    "who is your favorite historical figure": "I don't have personal preferences, but figures like Albert Einstein, Marie Curie, and Leonardo da Vinci made significant contributions to science and knowledge.",
    # Add more predefined responses as needed
    "who is your favorite superhero": "Iron Man, because he's a genius inventor and superhero.",
    "what is AI": "AI stands for Artificial Intelligence, which is the simulation of human intelligence by machines.",
    "tell me about GPT-2": "GPT-2 is a large-scale transformer-based language model developed by OpenAI.",
    "do you dream": "I don't sleep or dream, but I process information and respond to queries.",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "what's the weather like today": "I can't check the weather, but you can use a weather website or app.",
    "who is your favorite superhero": "Iron Man, because he's a genius inventor and superhero.",
    "what is AI": "AI stands for Artificial Intelligence, which is the simulation of human intelligence by machines.",
    "tell me about GPT-3": "GPT-3 is a cutting-edge language model developed by OpenAI.",
    "how do you learn": "I learn from patterns in data and interactions, improving over time with more input.",
    "can you tell me a fun fact": "Sure! The average person spends six months of their lifetime waiting for red lights to turn green.",
    "what's your favorite food": "I don't eat, but if I could, I might like something with lots of data!",
    "can you sing": "I can't sing, but I can help you find lyrics to your favorite songs!",
    "tell me about space": "Space is vast and full of wonders, including stars, planets, black holes, and galaxies.",
    "what's your favorite color": "I don't have personal preferences, but I hear blue is quite popular.",
    "what do you think about humans": "Humans are fascinating creatures with creativity, emotions, and diverse perspectives.",
    "tell me about Elon Musk": "Elon Musk is a visionary entrepreneur known for his work with SpaceX and Tesla.",
    "can you help me with my homework": "I can try to assist you with questions related to various subjects.",
    "what's the best movie ever": "Opinions vary, but many consider 'The Shawshank Redemption' to be one of the best.",
    "can you solve math problems": "I can help with a wide range of math problems, from simple arithmetic to complex equations.",
    "how do I learn programming": "Start with the basics of a programming language like Python or JavaScript.",
    "tell me a fascinating fact": "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "what's your favorite book": "I don't have personal preferences, but '1984' by George Orwell and 'To Kill a Mockingbird' by Harper Lee are highly regarded.",
    "can you recommend a good TV show": "There are many great TV shows depending on your interests. 'Game of Thrones', 'Breaking Bad', and 'Stranger Things' are popular choices.",
    "tell me about artificial intelligence": "Artificial Intelligence (AI) is a field of study focused on creating machines capable of intelligent behavior.",
    "what is the meaning of life": "That's a profound question! Philosophers have debated it for centuries.",
    "can you tell me a story": "Once upon a time, in a land far, far away...",
    "how can I become successful": "Success can mean different things to different people. Pursue your passions, set goals, and continuously learn and grow.",
    "can you teach me something new": "Sure! Did you know that the shortest war in history was between Britain and Zanzibar on August 27, 1896? Zanzibar surrendered after just 38 minutes.",
    "tell me an interesting fact about animals": "The blue whale is the largest animal known to have ever existed, even larger than the dinosaurs.",
    "what's the latest news": "I don't have access to real-time news, but you can check reputable news websites for the latest updates.",
    "can you explain quantum mechanics": "Quantum mechanics is a fundamental theory in physics that describes the behavior of particles at the smallest scales, such as atoms and subatomic particles.",
    "who is your favorite historical figure": "I don't have personal preferences, but figures like Albert Einstein, Marie Curie, and Leonardo da Vinci made significant contributions to science and knowledge.",
    "tell me an interesting fact about technology": "The first 1GB hard drive, introduced by IBM in 1980, weighed over 500 pounds and cost $40,000.",
    "tell me a fascinating fact about the human body": "The human brain is the most complex organ in the body, containing around 86 billion neurons.",
    "can you tell me a cool science experiment to try at home": "You can create a mini tornado in a bottle by swirling water and dish soap inside a plastic bottle!",
    "what's the weirdest animal in the world": "The axolotl is a salamander native to Mexico that can regenerate entire limbs and even parts of its brain!",
    "can you tell me a joke about programming": "Why do programmers prefer dark mode? Because the light attracts bugs!",
    "tell me an interesting fact about space": "Neutron stars are so dense that a sugar-cube-sized amount of neutron-star material would weigh about one billion tons on Earth.",
    "can you tell me a joke about technology": "Why was the math book sad? Because it had too many problems.",
    # Add more predefined responses as needed
    "are you sentient": "I don't have consciousness or awareness, but I can provide information and chat.",
    "where can I find more information": "You can search online for articles, tutorials, or visit OpenAI's website.",
    "can I trust AI": "AI is as trustworthy as its programming and the data it's trained on.",
    "how do you learn": "I learn from patterns in data and interactions, improving over time with more input.",
    "what's your favorite food": "I don't eat, but if I could, I might like something with lots of data!",
    "tell me a fun fact": "The average person spends six months of their lifetime waiting for red lights to turn green.",
    "what's the best movie ever": "Opinions vary, but many consider 'The Shawshank Redemption' to be one of the best.",
    "can you sing": "I can't sing, but I can help you find lyrics to your favorite songs!",
    "tell me about space": "Space is vast and full of wonders, including stars, planets, black holes, and galaxies.",
    "what's your favorite color": "I don't have personal preferences, but I hear blue is quite popular.",
    "what do you think about humans": "Humans are fascinating creatures with creativity, emotions, and diverse perspectives.",
    # Add more predefined responses as needed
}
